name: ffmpeg_kit_flutter_android
description: FFmpeg kit specifically for Android
repository: https://github.com/sk3llo/ffmpeg_kit_flutter
homepage: https://github.com/sk3llo/ffmpeg_kit_flutter
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ffmpeg_kit_flutter_platform_interface: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.ffmpegkit
        pluginClass: FFmpegKitFlutterAndroidPlugin